### ISSUE TITLE
First Name Last Name Not Showing in CP

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-akismet#12]
Using this in my config:
```
      'contact' => [
            'first_name_field' => 'first_name',
            'last_name_field' => 'last_name',
            'email_field' => 'email',
            'content_field' => 'c_message',
        ],
```
This is all I ever see in the CP for submissions marked as spam.

![123](https://user-images.githubusercontent.com/16004958/94193881-24792c00-fe6e-11ea-9edb-84c7e5a5d456.png)

**Comment by edalzell** [comment]
In 2.2
