### ISSUE TITLE
Have to Delete Spam Queue Items One at a Time

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-akismet#14]
It looks like there is a select all checkbox but it doesn't do anything. I have to delete messages in each spam queue one at a time. It says I have 40 now and there is no way I'm going to take the time to click the three little dots and discard for each one.

**Comment by edalzell** [comment]
Note to self, this is because I've copied the table from the forms but haven't figured out how to wire up the delete.

**Comment by edalzell** [comment]
in 2.2.1
