### ISSUE TITLE
Mark as spam action appears in Collection listing

### ISSUE THREAD

**Issue by mikemartin** [silentzco/statamic-akismet#15]
It seems that the "Mark as Spam" action is showing in all Table listings.

<img width="1034" alt="Screen Shot 2020-10-21 at 10 35 19 am" src="https://user-images.githubusercontent.com/414211/96655436-31177400-1389-11eb-881a-f6cc4ebd2f22.png">

<img width="1021" alt="Screen Shot 2020-10-21 at 10 35 24 am" src="https://user-images.githubusercontent.com/414211/96655432-2e1c8380-1389-11eb-8d7c-84ec3c731e5d.png">

**Comment by edalzell** [comment]
In 2.2
