### ISSUE TITLE
Can't update to 2.2.2 from 2.1 via cli

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-akismet#20]
I'm on 2.1. I just went to update to 2.2.2 and I can't. First I thought it was because I had "silentz/akismet": "^2.0" in my composer.json but then I changed that to "silentz/akismet": "2.0.*" and it downgraded me to 2.0.1. Then I tried "silentz/akismet": "^2.2" and I got:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install silentz/akismet v2.2.2
    - Conclusion: don't install silentz/akismet v2.2.1
    - Conclusion: remove nikic/php-parser v4.9.1
    - Installation request for silentz/akismet ^2.2 -> satisfiable by silentz/akismet[v2.2, v2.2.1, v2.2.2].
    - Conclusion: don't install nikic/php-parser v4.9.1
    - silentz/akismet v2.2 requires stillat/proteus ^1.0 -> satisfiable by stillat/proteus[v1.0.0, v1.0.1].
    - stillat/proteus v1.0.0 requires nikic/php-parser ^4.10 -> satisfiable by nikic/php-parser[v4.10.0, v4.10.1, v4.10.2].
    - stillat/proteus v1.0.1 requires nikic/php-parser ^4.10 -> satisfiable by nikic/php-parser[v4.10.0, v4.10.1, v4.10.2].
    - Can only install one of: nikic/php-parser[v4.10.0, v4.9.1].
    - Can only install one of: nikic/php-parser[v4.10.1, v4.9.1].
    - Can only install one of: nikic/php-parser[v4.10.2, v4.9.1].
    - Installation request for nikic/php-parser (locked at v4.9.1) -> satisfiable by nikic/php-parser[v4.9.1].

**Comment by edalzell** [comment]
FYI, this is not really an Akismet problem, you've got something funky w/ your packages.

What does `composer why nikic/php-parser` give you?

**Comment by twd3** [comment]
PS C:\_statamic\v-3> composer why nikic/php-parser
**psy/psysh  v0.10.4  requires  nikic/php-parser (~4.0|~3.0|~2.0|~1.3)**
PS C:\_statamic\v-3> composer why psy/psysh
**laravel/tinker  v2.4.2  requires  psy/psysh (^0.10.3)**

**Comment by edalzell** [comment]
from your site folder, `rm -rf vendor composer.lock && composer install`

**Comment by twd3** [comment]
Can't run that on Windows. Is it just deleting something and running composer install?

**Comment by edalzell** [comment]
Yes, the `vendor` folder and the `composer.lock` file.

**Comment by twd3** [comment]
That worked.
