### ISSUE TITLE
Can't update statamic after updating Akismet

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-akismet#26]
Just tried updating Statamic to 3.0.38 and couldn't because of this error:

```
PHP Fatal error:  Access level to Silentz\Akismet\ServiceProvider::bootActions() must be protected (as in class Statamic\Providers\AddonServiceProvider) or weaker in C:\_statamic\v-3\vendor\silentz\akismet\src\ServiceProvider.php on line 58In ServiceProvider.php line 58:
  Access level to Silentz\Akismet\ServiceProvider::bootActions() must be protected (as in class Statamic\Providers\Ad
  donServiceProvider) or weaker
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

**Comment by twd3** [comment]
And I should say this broke the frontend and CP. It was working after just updating Akismet to 3.0.1. But then when I attempted to update Statamic to 3.0.38 after updating Akismet I got the error above and can't access the site. Never pushed changes so only local busted (learning lol).

**Comment by twd3** [comment]
![image](https://user-images.githubusercontent.com/16004958/104246356-13efc000-5423-11eb-8fe5-136b100a9457.png)

**Comment by edalzell** [comment]
Fixed in https://github.com/silentzco/statamic-akismet/commit/e6250111cc5a236b20219d3934bc2b7fb1111b2f
