### ISSUE TITLE
Error during installation and configuration not working (issue with Forma?)

### ISSUE THREAD

**Issue by corazzi** [silentzco/statamic-akismet#30]
Hi,

I'm having an issue installing and using this addon. When I install it, I get an error during the package discovery stage. The installation seemingly fails and reverts, but the addon and its dependency Forma are both shown as installed in the CP.

The configuration form doesn't work properly, and there doesn't seem to be all the settings the addon should provide. It looks like it's mainly Forma causing the issue, as that what causes the composer failure, but I can't tell for sure.

**Environment**
Statamic 3.0.47
Laravel 7.30.4
PHP 7.4.13
Laravel Valet 2.11.0 
macOS Big Sur 11.2.3
No other addons installed

_(NB: also tried PHP 7.4.9 on Ubuntu 20.04.1 with Laravel Forge with the same results)_

**Steps to reproduce**
1. Run `composer require silentz/akismet` on the command line (or within the CP)
2. Installation fails and `composer.json` is reverted <sup>1</sup>
3. Run `php artisan vendor:publish --tag="akismet-config"` anyway
4. The config file is published
4. Refresh the Statamic CP
5. Under Addons, Akismet and Forma are "installed" <sup>2</sup>
6. In the CP navigation, there is an Akismet item under Addon Settings <sup>3</sup>
7. Add `AKISMET_API_KEY` to `.env` file
8. Go to `/cp/akismet/config/edit`
9. Form loads but doesn't show API key value (even after clearing config cache)
10. Entering values into the Forms section updates the config file but, after refreshing the config page, these values don't populate the form

<sup>1</sup> Output from `composer require silentz/akismet`:
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Return value of Edalzell\Forma\FormaAddon::getAddon() must be an instance of Statamic\Extend\Addon, null returned

  at vendor/edalzell/forma/src/FormaAddon.php:45
    41|     }
    42|
    43|     private function getAddon(): Addon
    44|     {
  > 45|         return Blink::once($this->addon, fn () => AddonAPI::get($this->addon));
    46|     }
    47|
    48|     private function registerRoutes()
    49|     {

      +14 vendor frames
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

<sup>2</sup> Addons page
![image](https://user-images.githubusercontent.com/915909/111278237-3a072b80-8631-11eb-83fc-1a1af2478058.png)

<sup>3</sup> CP Menu
![image](https://user-images.githubusercontent.com/915909/111278575-98340e80-8631-11eb-8195-3d74012ccfc0.png)

**Comment by edalzell** [comment]
Thanks for this report.

As a temp work around, please try to install it again `composer require silentz/akismet`. Error doesn't occur on the second time, for some reason.

**Comment by corazzi** [comment]
Thanks @edalzell, that seems to have done the trick :)

**Comment by edalzell** [comment]
I've pushed an update to Forma that should work now on the next site you need it to!
