### ISSUE TITLE
Spam Submissions not flagged as spam

### ISSUE THREAD

**Issue by knieth** [silentzco/statamic-akismet#31]
Hello,

We're having issues with the addon.

**Environment**
Statamic 3.1.18
PHP 7.4.14

**Installation steps we've made:**
- Installed via composer - composer require silentz/akismet
- Added AKISMET_API_KEY in .env
- Published the config(config/akismet.php) - php artisan vendor:publish --tag="akismet-config"

**Current config**

![image](https://user-images.githubusercontent.com/17942162/121516796-35c88f80-ca21-11eb-882c-e848ea7c2946.png)

![image](https://user-images.githubusercontent.com/17942162/121516952-60b2e380-ca21-11eb-81c6-79190a615473.png)

**Issues we've encountered:**

Spam submission are not flagged as spam.
http://share.iation.com/v/DdDuuR6uRm2A9BhBdgI7

Only manual marking spams currently works, and if there's spams clicking the 'Spam Queue' throws an error, need to directly go to the specific form spam queue.
http://share.iation.com/v/VqMTktBELvefGW7mQA19

**Comment by edalzell** [comment]
> clicking the 'Spam Queue' throws an error

What error?

**Comment by edalzell** [comment]
Opened a new issue for the SVG

**Comment by edalzell** [comment]
@knieth can I see your form template please?

**Comment by edalzell** [comment]
Also, can you please try with `akismet-guaranteed-spam@example.com` as the email address or `viagra-test-123` as the name as see if those are flagged as spam?

**Comment by sigalkel** [comment]
Hi there,
We just bought the statamic addon and are seeing the exact same issue.

1. using the test values: akismet-guaranteed-spam@example.com as the email or viagra-test-123 as name doesn't move the contact forms into the spam queue.

2. Clicking on the smap queue gives us the following error:
Call to a member function handle() on null (View: D:\xampp80\htdocs\MakeYourself\vendor\silentz\akismet\resources\views\cp\queues\index.blade.php)

Please can you advice?

Many thanks
Sigal

**Comment by sigalkel** [comment]
Hi there,
We just bought the statamic addon and are seeing the exact same issue.

using the test values: akismet-guaranteed-spam@example.com as the email or viagra-test-123 as name doesn't move the contact forms into the spam queue.

Clicking on the smap queue gives us the following error:
Call to a member function handle() on null (View: \vendor\silentz\akismet\resources\views\cp\queues\index.blade.php)

Please can you advice?

Many thanks
Sigal

**Comment by edalzell** [comment]
hey @sigalkel can I see the `akismet.php` config file?

p.s. I moved your other problem to a new issue.

**Comment by edalzell** [comment]
@sigalkel can I see your `akismet.php` config file please?

**Comment by sigalkel** [comment]
[akismet.zip](https://github.com/silentzco/statamic-akismet/files/7194639/akismet.zip)

**Comment by edalzell** [comment]
Can you please zip up your site (please remove the `node-modules` and `vendor` folders) and send it to me?

**Comment by sigalkel** [comment]
Hi Erin, did you get my files?

**Comment by edalzell** [comment]
Yup, will be looking this week.

**Comment by edalzell** [comment]
The Akismet key you have in the .env is incorrect. When I use my Akismet key everything works as expected. With yours I get an `invalid` error on the call to Akismet.

Please double check the key.

**Comment by edalzell** [comment]
Not the Akismet license key the Akismet API key

<img width="735" alt="CleanShot 2021-09-27 at 10 39 49@2x" src="https://user-images.githubusercontent.com/6069653/134958326-463c7f6f-7fa9-42a3-8e12-4cf87989b492.png">

**Comment by sigalkel** [comment]
Now, the API key showed up on https://akismet.com/account/ and I put it in the env file, cleared all caches including config but still getting the same error in the spam queue.

**Comment by edalzell** [comment]
> Now, the API key showed up on https://akismet.com/account/ and I put it in the env file, cleared all caches including config but still getting the same error in the spam queue.

Wrong issue for this comment, that's this issue: https://github.com/silentzco/statamic-akismet/issues/34

**Comment by knieth** [comment]
@edalzell here is the contact form template

Also I already tried testing with `akismet-guaranteed-spam@example.com` as the email address or `viagra-test-123` as the name, the submission still not getting flagged as spam.

![image](https://user-images.githubusercontent.com/17942162/136377529-3ac61e7f-7503-4b74-998a-4291498297da.png)
![image](https://user-images.githubusercontent.com/17942162/136377719-877b37ff-836a-4ef1-91b3-5c2f34b4038d.png)



```
        <div class="contact-form" id="contact_form">

            {{ form:create in="contact" redirect="/contact#contact_form_container" error_redirect="/contact#contact_form_container" }}

              {{ if errors }}
                  <div class="callout alert">
                      <p>
                        {{ errors }}
                            {{ value }}<br>
                        {{ /errors }}
                      </p>
                  </div>
              {{ /if }}

              {{ if success }}
                  <div class="callout success">
                      <p>
                          Thank you for contacting us, we will be in touch.
                      </p>
                  </div>
              {{ /if }}

              <div class="row">
                <div class="large-6 columns">
                  <label>Name</label>
                  <input type="text" id="name" name="name" value="{{ old:name }}" autofocus required>
                </div>
                <div class="large-6 columns">
                  <label>Email Address</label>
                  <input type="text" id="email" name="email" value="{{ old:email }}" required>
                </div>
                <div class="large-12 columns">
                  <label>Message</label>
                  <textarea id="message" name="message" required>{{ old:message }}</textarea>
                </div>
                <div class="large-12 columns">
                  {{ captcha }}<br>
                </div>
                <div class="large-12 columns">
                  <input type="text" name="honeypot" style="display: none;"/>
                  <input type="submit" class="button" value="Submit">
                </div>
              </div>
            {{ /form:create }}

        </div>
```

**Comment by edalzell** [comment]
@knieth this is the Aksimet API key NOT the license key from Statamic right?
<img width="217" alt="CleanShot 2021-10-10 at 12 41 14@2x" src="https://user-images.githubusercontent.com/6069653/136710828-f83cbd83-b2f8-493b-bd43-ed712ffacf66.png">

**Comment by knieth** [comment]
@edalzell, yes that is NOT the license key from Statamic, that is the API key from the Akismet account, that is the only key we can find in our Akismet account.

**Comment by edalzell** [comment]
@knieth can you please zip up your site (don't send the node_modules or vendor folder) and send to me?

**Comment by thestepafter** [comment]
@edalzell I have shared a Dropbox link directly with you for the site referenced by @knieth.

Thank you!

**Comment by edalzell** [comment]
@knieth @thestepafter while I **can** reproduce the issue, if I upgrade to Statamic 3.2 form submissions are correctly flagged as spam.

Are you able to upgrade to 3.2? You should as 3.1 is quite old.

**Comment by knieth** [comment]
@edalzell, confirmed that upgrading to 3.2 solved the issue, thank you.
