### ISSUE TITLE
Unable to delete spam in the queue via one at a time or bulk options

### ISSUE THREAD

**Issue by michaelkrol** [silentzco/statamic-akismet#33]
To empty the Spam Queue,  the documentation states "Both of those can be done one at a time, or in bulk via the bulk selection." but there does not appear to be any "Bulk" option. Has this been removed from the Addon for some reason? In the queue there is an option to check the box and select all messages, but once checked there is nothing you can do. There is no "Empty Queue" or "Delete All" option. Am I missing something? 

<img width="954" alt="Screen Shot 2021-07-16 at 9 26 29 AM" src="https://user-images.githubusercontent.com/1694013/125979420-e1334621-96fd-4371-9def-b9370d585d63.png">

To further complicate the issue, trying to delete spam one at a time also results in a Javascript error: 

`Actions.js:60 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at Actions.js:60`

So there does not appear to be any way to delete spam in the queue, either one at a time or in bulk? 

We're running Statamic 3.1.27 on PHP 7.4.16

**Comment by edalzell** [comment]
Confirmed, looking into it.
