### ISSUE TITLE
Visiting Spam Queue throws an error

### ISSUE THREAD

**Issue by edalzell** [silentzco/statamic-akismet#34]
Clicking on the spam queue gives us the following error:
Call to a member function handle() on null (View: \vendor\silentz\akismet\resources\views\cp\queues\index.blade.php)

_Originally posted by @sigalkel in https://github.com/silentzco/statamic-akismet/issues/31#issuecomment-921898853_

**Comment by edalzell** [comment]
@sigalkel can I see that error in the error log please? The top bunch of lines, like the top 15 or so.

**Comment by sigalkel** [comment]
[queue_error_log.txt](https://github.com/silentzco/statamic-akismet/files/7194663/queue_error_log.txt)

**Comment by edalzell** [comment]
Can you please zip up your storage folder and send it to me?

**Comment by sigalkel** [comment]
Hi Erin, did you get my files?

**Comment by edalzell** [comment]
Yup, will look in the next few days

**Comment by edalzell** [comment]
I can't reproduce this with the site you sent me

<img width="1099" alt="CleanShot 2021-09-26 at 10 53 04@2x" src="https://user-images.githubusercontent.com/6069653/134818663-b482d7b6-429e-4b71-ac31-590005865544.png">

Does it happen when every user?

**Comment by sigalkel** [comment]
It happens with the 2 test examples of spam email and spam name you've supplied in the documentation.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by edalzell** [comment]
I don't get the spam queue error. You're talking about the other issue of spam not getting flagged.
