### ISSUE TITLE
Unable to install Statamic 3.3

### ISSUE THREAD

**Issue by tomagig** [silentzco/statamic-akismet#36]
composer require silentz/akismet

Using version ^3.0 for silentz/akismet
./composer.json has been updated
Running composer update silentz/akismet
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - silentz/akismet v3.0 requires php ^7.4 -> your php version (8.1.4) does not satisfy that requirement.
    - silentz/akismet[v3.0.1, ..., v3.0.6] require edalzell/forma ^0.8 -> found edalzell/forma[v0.8, ..., v0.8.12] but the package is fixed to v1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - silentz/akismet[v3.0.7, ..., v3.0.8] require laravel/framework ^7.30.3 || ^8.40 -> found laravel/framework[v7.30.3, ..., 7.x-dev, v8.40.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
    - Root composer.json requires silentz/akismet ^3.0 -> satisfiable by silentz/akismet[v3.0, ..., v3.0.8].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require silentz/akismet:*" to figure out if any version is installable, or "composer require silentz/akismet:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by edalzell** [comment]
Try version 3.1. Actual issue was missing Laravel 9 support.

**Comment by tomagig** [comment]
I ran composer update and then tried installing again and met with the following error:

composer require silentz/akismet
Using version ^3.1 for silentz/akismet
./composer.json has been updated
Running composer update silentz/akismet
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nickurt/laravel-akismet[1.8.0, ..., 1.9.0] require php ^7.2 -> your php version (8.1.4) does not satisfy that requirement.
    - nickurt/laravel-akismet 1.10.0 requires laravel/framework ^6.0|^7.0|^8.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
    - silentz/akismet v3.1 requires nickurt/laravel-akismet ^1.8 -> satisfiable by nickurt/laravel-akismet[1.8.0, 1.9.0, 1.10.0].
    - Root composer.json requires silentz/akismet ^3.1 -> satisfiable by silentz/akismet[v3.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require silentz/akismet:*" to figure out if any version is installable, or "composer require silentz/akismet:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by edalzell** [comment]
Dependencies updated, try again
