### ISSUE TITLE
FR: Opinionated UI Stuff

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-akismet#9]
In my opinion, I think when you click on Spam Queue it should just open that menu showing your forms, and then if any of the forms have spam just put a little pill with the current number of spam messages to the right like how updates show up. I keep finding myself clicking spam queue and just seeing a blank page.
![pill](https://user-images.githubusercontent.com/16004958/93268986-60740900-f76b-11ea-97c7-8719386ef6c6.jpg)

**Comment by edalzell** [comment]
That's what happens already: 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/6069653/93269424-ce1c3700-f763-11ea-92f0-653547730835.png">

The page is blank because there is no spam in the queue. Perhaps that can be cleaned up

**Comment by twd3** [comment]
No, you have 3 spams in contact us and there's no little red square next to contact us in the left menu like updates has a one...

**Comment by twd3** [comment]
Also, if you click on one of the forms it would be great if that menu stayed open and the form you're on, text is bold.

**Comment by edalzell** [comment]
Fixed in 2.1
